sudo: false
language: python
python:
- 2.7
install:
- git clone --single-branch https://github.com/grow/pygrow.git
- cd pygrow
- travis_retry pip install -r requirements.txt
- python setup.py install
- cd ..
script:
- ./pygrow/bin/grow build
